project:
  type: book

book:
  title: "R for Geospatial Data Science and Analytics"
  author: "Dr. Kam Tin Seong"
  date: "12/8/2022"
  chapters:
    - index.qmd
    - part: "The Building Block"
      chapters: 
      - chap01.qmd
      - chap02.qmd
      - chap03.qmd
    - part: "Spatial Point Patterns Analysis"
      chapters:
      - chap04.qmd
      - chap05.qmd
      - chap06.qmd
      - chap07.qmd
    - part: "Spatial Weights and Applications" 
      chapters:
      - chap08.qmd
      - chap09.qmd
      - chap10.qmd
    - part: "Geospatial Multivariate Data Analysis"
      chapters:
      - chap11.qmd
      - chap12.qmd
    - part: "Geographically Weighted Models"
      chapters:
      - chap13.qmd
      - chap14.qmd
    - part: "Modelling Spatial Interaction and Flows"
      chapters:
      - chap15.qmd
      - chap16.qmd
      - chap17.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

