---
title: "Spatio-Temporal Point Patterns Analysis"
date: "July 21, 2024"
date-modified: "last-modified"
format: html
execute:
  message: false
  warning: false
  freeze: true
editor: visual
---

## Overview

A spatio-temporal point process (also called space-time or spatial-temporal point process) is a random collection of points, where each point represents the time and location of an event. Examples of events include incidence of disease, sightings or births of a species, or the occurrences of fires, earthquakes, lightning strikes, tsunamis, or volcanic eruptions. 

The analysis of spatio-temporal point patterns is becoming increasingly necessary, given the rapid emergence of geographically and temporally indexed data in a wide range of fields. Several spatio-temporal point patterns analysis methods have been introduced and implemented in R in the last ten years.  This chapter shows how various R packages can be combined to run a set of spatio-temporal point pattern analyses in a guided and intuitive way.  A real world forest fire events in Kepulauan Bangka Belitung, Indonesia from 1st January 2023 to 31st December 2023 is used to illustrate the methods, procedures and interpretations.

## Learning Outcome

### The research questions

The specific question we would like to answer is:

-   are the locations of forest fire in Kepulauan Bangka Belitung spatial and spatio-temporally independent?
-   if the answer is NO, where and when the observed forest fire locations tend to cluster?

### The data

For the purpose of this exercise, two data sets are used, they are:

-   forestfires, a csv file provides locations of forest fire detected from the Moderate Resolution Imaging Spectroradiometer (MODIS) sensor data.  The data are downloaded from [Fire Information for Resource Management System](https://firms.modaps.eosdis.nasa.gov/download/).  For the purpose of this exercise, only forest fires within Kepulauan Bangka Belitung will be used.  
-  Kepulauan_Bangka_Belitung, an ESRI shapefile showing the sub-district (i.e. [kelurahan](https://en.wikipedia.org/wiki/Villages_of_Indonesia)) boundary of Kepulauan Bangka Belitung.  The data set was downloaded from [Indonesia Geospatial](https://www.indonesia-geospasial.com/2023/05/download-shapefile-batas-administrasi.html) portal. The original data covers the whole Indonesia.  For the purpose of this exercise, only sub-districts within Kepulauan Bangka Belitung are extracted.

## Installing and Loading the R packages

For the purpose of this study, five R packages will be used. They are:

-   rgdal for importing geospatial data in GIS file format such as shapefile into R and save them as Spatial\*DataFrame,
-   maptools for converting Spatial\* object into ppp object,
-   raster for handling raster data in R,
-   spatstat for performing Spatial Point Patterns Analysis such as kcross, Lcross, etc., and
-   tmap for producing cartographic quality thematic maps.

```{r}
pacman::p_load(sf, raster, spatstat, tmap, tidyverse)
```

## Importing the Geospatial Data

## Mapping the geospatial layers

## Spatial Data Wrangling
